#pragma once
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <Windows.h>
#include <fstream>
#include <fileapi.h>
#include <Windows.h>
#include <algorithm>
#include <filesystem>
#include "zlib/include/zlib.h"
#include "zlib/include/zconf.h"
#include <iomanip>